const {GoogleGenAI} = require('@google/genai')

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY});

const jobSummarizer = async (req , res) => {

  const jobDescription = req.body;

  // console.log(jobDescription);
 
  const prompt = `Job Description : ${jobDescription} based on this job descriptions give me 10 keywords and then 5 keypoints that i can mention in my resume so my resume selection chances increase , givem answer and remove all preambles or fillers;`


  console.log(prompt);
  
  async function main() {
    const response = await ai.models.generateContent({
      model: "gemini-2.0-flash",
      contents: prompt,
    });
    // console.log(response.text);

    /* textResult is the response generated by gemini api */
    const textResult = await response.text;

    /* textResult raw format is hard to understand to we have to beautify it */
    /* first with cleanedText we will replace "**" with '' */
    const cleanedText = textResult.replace(/\*\*/g, "");
    console.log(cleanedText);

    const cleanerText = cleanedText.replace(/\\n/g, '\n');
    console.log(cleanerText);

    // const parsedText = JSON.parse(cleanerText);

    res.status(201).json({
      success : true,
      message : cleanerText,
    })
  }
  
  main();

}


module.exports = {jobSummarizer};