import React, { useState } from 'react'
import ProfileRightBlock from "./ProfileRightBlock";

const GenerateResumeForm = () => {

  const [done , setDone] = useState(true);

  return (
    <>
      {done ? (<div className="h-screen w-full hidden md:flex justify-around bg-gray-500 p-7">
      <div className='w-[25%] h-full  rounded-2xl'>
        <div className='w-full p-7 h-[50%] bg-red-500 rounded-md shadow-xl shadow-black'>
          <p className='text-xl font-bold'>Job Description : </p> 
          <textarea
            name=""
            id=""
            autoComplete="none"
            placeholder="Copy & Paste the Job Description Here ..."
            className=" border-2 mt-2 h-[90%] w-[100%] resize-none p-3 outline-none rounded-lg font-bold bg-gray-700 placeholder:text-gray-900 "
          ></textarea> 
        </div>
        <button className='mt-10 border-3 text-xl font-bold pt-3 pb-3 pl-10 pr-10 rounded-xl shadow-xl shadow-black bg-blue-500' >Generate</button>

        {/* below div contain the document generated by the ai  */}
        <div className='mt-10 h-[35%] w-full bg-red-500 rounded-xl p-3 '>

        </div>

      </div>
      <ProfileRightBlock />
    </div>) : (<div className="h-screen text-2xl font-bold flex justify-center items-center">Under Making .........</div>)}
    </>
    
  )
}

export default GenerateResumeForm